# Конфігурація для патернів
WINDOW_EXTREMUM = 20  # Вікно для екстремумів - 20
STEP_FOR_HEAD_AND_SHOULDERS = 1  # Крок для голови і плечей
HEAD_AND_SHOULDERS_THRESHOLD = 0.01  # Різниця між плечами
WINDOW_RSI = 10
EMA_SHORT_PERIOD = 12
EMA_LONG_PERIOD = 26

# Початкові параметри для аналізу
INITIAL_BALANCE = 100.0
STAKE_MULTIPLIER_START = 1.0
PERCENT_OF_BALANCE_FOR_BET = 15
PERCENT_STOP_LOSS = 10
PERCENT_TAKE_PROFIT = 10
TRAILING_STOP_LOSS_PERCENT = 30
TRAILING_STOP_LOSS_PERCENT_FOR_POSITIVE_FILTER = 30
TRAILING_STOP_LOSS_PERCENT_FOR_NEGATIVE_FILTER = 30
RSI_FOR_INCREASE_TRAILING_PERCENT_ON_LONG = 30
RSI_FOR_DECREASE_TRAILING_PERCENT_ON_LONG = 70
RSI_FOR_INCREASE_TRAILING_PERCENT_ON_SHORT = 70
RSI_FOR_DECREASE_TRAILING_PERCENT_ON_SHORT = 30
RSI_FOR_CLOSING_LONG = 50
RSI_FOR_CLOSING_SHORT = 50

# Інші чарівні значення можуть бути додані тут у майбутньому
TIMEFRAME = '2h'
LIMIT_CANDLES = 1000
